version: '3'

volumes:
  postgres_volume:

services:
  pg:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    image: ${REGISTRY}/${MIGRATOR_IMAGE_NAME}:${TAG_NAME}
    restart: on-failure
    environment:
      db_host: pg

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${REGISTRY}/${SERVER_IMAGE_NAME}:${TAG_NAME}
    container_name: ${SERVER_CONTAINER_NAME}
    ports:
      - "50051:50051"